server:
  port: 8761

spring:
  application:
    name: discovery-service
  security:
    user:
      name: ${USERNAME_}
      password: ${PASSWORD_}

eureka:
  instance:
    hostname: ${DISCOVERY_HOST}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${DISCOVERY_HOST}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    org.springframework.security: WARN
    com.netflix.discovery: INFO
